export default defineAppConfig({
  pages: [
    'pages/login/index',
    'pages/register/index',
    'pages/home/index',
    'pages/diary/index',
    'pages/time-letters/index',
    'pages/notifications/index',
    'pages/points/index',
    'pages/profile/index',
    'pages/create-companion/index',
    'pages/generation-progress/index',
    'pages/scan-friend/index',
    'pages/add-friend-qr/index',
    'pages/edit-profile/index',
    'pages/change-password/index',
    'pages/empty-cat/index',
    'pages/welcome/index',
    'pages/upload-material/index',
    'pages/cat-player/index',
    'pages/cat-history/index',
    'pages/switch-companion/index',
    'pages/accompany-milestone/index',
    'pages/notification-list/index',
    'pages/privacy-settings/index',
    'pages/privacy-policy/index',
    'pages/terms-of-service/index',
    'pages/reset-password/index',
    'pages/download/index',
    'pages/feedback/index',
    'pages/join-friend/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#FFF9F5',
    navigationBarTitleText: 'Miao',
    navigationBarTextStyle: 'black',
    backgroundColor: '#FFF9F5',
  },
  tabBar: {
    color: '#8E8E8E',
    selectedColor: '#E89F71',
    backgroundColor: '#FFFFFF',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/diary/index',
        text: '日志',
        // iconPath: 'assets/icons/diary.png',
        // selectedIconPath: 'assets/icons/diary-active.png',
      },
      {
        pagePath: 'pages/time-letters/index',
        text: '时光',
        // iconPath: 'assets/icons/letter.png',
        // selectedIconPath: 'assets/icons/letter-active.png',
      },
      {
        pagePath: 'pages/home/index',
        text: '首页',
        // iconPath: 'assets/icons/home.png',
        // selectedIconPath: 'assets/icons/home-active.png',
      },
      {
        pagePath: 'pages/points/index',
        text: '积分',
        // iconPath: 'assets/icons/points.png',
        // selectedIconPath: 'assets/icons/points-active.png',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        // iconPath: 'assets/icons/profile.png',
        // selectedIconPath: 'assets/icons/profile-active.png',
      },
    ],
  },
  });